### PR TITLE
Changes required by witnet-rust

### LINKED ISSUE #1: Potential runtime panic detected by static analysis
The following code would call unwrap on None:
```rust
use scriptful::op_systems::pokemon::{pokemon_op_sys, Command::*};
use scriptful::prelude::*;

fn main() {
    let mut machine = Machine::new(&pokemon_op_sys);
    machine.operate(&Item::Operator(Evolute));
}
```

### LINKED ISSUE #2: Allow using external context inside operator_system function
Allow some mechanism to pass external state to the operator_system function:

```rust
fn my_operator_system<T>(context: T, stack: &mut Stack<MyValue>, operator: &MyOperator) {
    // TODO
}

let context = || block.timestamp;
let mut machine = Machine::new(|stack, op| my_operator_system(context, stack, op));
```

Maybe it can be implemented as a method of `Stack` to avoid changing the function signature:

```rust
fn my_operator_system(stack: &mut Stack<MyValue>, operator: &MyOperator) {
    let context = stack.context();
}
```

### LINKED ISSUE #3: Derive Clone for Item

### LINKED ISSUE #4: Derive Serialize/Deserialize for Item
This line doesn't work because it is impossible to enable the "use_serde" feature, as it is not defined in Cargo.toml

https://github.com/aesedepece/scriptful/blob/7c12e3d73c54818b1094bb3af3fadcbe32bf96db/src/core/item.rs#L14

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Close #1
Close #2
Close #3
Close #4

### CODE REVIEW

**Review by aesedepece — APPROVED** [review]

**Comment by aesedepece** [comment]
@tmpolaczyk Feel free to merge, then I'll release this and you'll be able to update your PR in witnet-rust so that it becomes easier for other people to test the PR without checking out this branch locally. Thanks!

**Comment by tmpolaczyk** [comment]
Perfect! I don't have merge permissions, can you do the merge?

**Comment by aesedepece** [comment]
> Perfect! I don't have merge permissions, can you do the merge?

Done!

**Comment by aesedepece** [comment]
v0.4.0 is now live on [crates.io](https://crates.io/crates/scriptful)

**Pull request merged**
